[package]
name = "rust-dll-demo"
version = "0.1.0"
edition = "2018"
authors = ["Rolf Karp <rolf.karp@gmail.com>"]
publish = false

[dependencies]
#winapi = { version = "0.3.9", features = ["minwindef", "fileapi", "winnt", "handleapi", "winbase", "processenv", "libloaderapi", "wingdi", "winuser"] }
windows = { github = "microsoft/windows-rs", version = "0.58.0", features = ["Win32_System_Console", "Win32_System_SystemServices", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_Security", "Win32_System_Memory", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug", "Win32_Graphics", "Win32_Graphics_OpenGL", "Win32_UI", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_Globalization", "Win32_System_ProcessStatus"] }
hudhook = { version = "0.7.1", features = ["opengl3"] }
tracing-subscriber = "0.3.18"

#minhook_raw = {version = "0.3.0"}
#glium = "0.34.0"
#libc = "0.2.155"
#glu-sys = "0.1.4"
[lib]
crate-type = ["cdylib"]


[profile.dev]
debug = true

[profile.release]
lto = true
debug = true  # Enable debug information for release profile