name: Rust Release
runs-on: windows-latest
on: push
#on:
  #push:
    #tags: "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
          - i686

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Rust Toolchain
        run: rustup default stable-${{ matrix.arch }}-pc-windows-msvc

      - name: run-vcpkg
        uses: lukka/run-vcpkg@66b1ea8d89609e8adecfeb38797f4479f447a374
        with:
          vcpkgTriplet: x86-windows-static-md

      - name: Fetch vcpkg dependencies
        run: vcpkg integrate install

      - name: Fetch vcpkg dependencies
        run: vcpkg install freetype

      - name: Build Release Artifacts
        run: cargo build --release

      - name: Create Release Archive
        run: |
          Get-ChildItem -Path "target/release/" -Filter "*.dll" | Select-Object -First 1 | ForEach-Object { Compress-Archive -Path $_.FullName -DestinationPath ("${{ matrix.arch }}" + ".zip") }

      - name: Generate Changelog
        run: git log -1 --pretty=format:"%s%n%b" > CHANGELOG.md

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          prerelease: false
          files: ${{ matrix.arch }}.zip
          fail_on_unmatched_files: true
